spring.application.name=backend
# Database Configuration - Render PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7hgdkdckfvc73ej48o0-a.singapore-postgres.render.com:5432/queue_db_o9a4?sslmode=require
spring.datasource.username=queue_db_o9a4_user
spring.datasource.password=UzjG3GJWTWk4L2ULeckWMZLmZqOdgQVj
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8083

# Seed Data
SEED_ADMIN_PASSWORD=admin123
SEED_DOCTOR_PASSWORD=doctor123

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Email (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sdharanish7@gmail.com
spring.mail.password=mhwx bayw sylf lxyx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=sdharanish7@gmail.com

# Supabase Configuration
supabase.url=https://dnmlblatwjjhuapuvxwi.supabase.co
supabase.key=sb_publishable_9cWAn0MVHIRrUtEovO7ROQ_P1sybvYy
supabase.jwt.secret=your-jwt-secret-here
